FROM node:16.15-alpine3.14
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
RUN npm install --save pm2
COPY . .
RUN npm run build
EXPOSE 5000 3020
CMD [ "node", "index.js" ]
